---
name: herd
services:
  server:
    container_name: ${CONTAINER_NAME:-server}
    build:
      context: .
    ports:
      - 50051:50051
    volumes:
    - log:/app/log

volumes:
  log:
