---
name: herd
services:
  server:
    container_name: ${CONTAINER_NAME:-server}
    build:
      context: .
      args:
        useLogging: ${USE_LOGGING:-true}
        useSecurity: ${USE_SECURITY:-true}
    ports:
      - "7878:7878"
    volumes:
      - log:/app/log

volumes:
  log: