---
name: Lint & Test
on:
  pull_request:
    branches: [ "*" ]

env:
    GOVERSION: "1.19"

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=${{ env.GOVERSION }}'
        check-latest: true
    - name: Test
      run: go test -v -race ./...


